### ISSUE TITLE
autopopulate Abstract with Description

### ISSUE THREAD

**Issue by kelle** [PressForward/PF_Zenodo#4]
we are happy with the default text for the "Abstract" to be the first 160 characters which are provided in the Description field.
It didn't happen for this post:
http://www.astrobetter.com/blog/2015/09/30/aerphd-part1/

**Comment by LibrarPotter** [comment]
"Enter an abstract, if applicable." Implies that no abstract is required.  Since an abstract is required by Zenodo, could this be updated to "Enter an abstract or description", or will this be auto-completed behind the scenes if it is left blank?

No abstract was auto-filled for this post: http://womeninastronomy.blogspot.com/2016/03/postdoctoral-fellow-highlight-dr-lia.html

**Comment by kelle** [comment]
I think this is done. Close?
